sudo: required

language: node_js
node_js:
  - "7"

install:
  - npm install --only=dev

services:
  - docker

after_success:
  - docker ps -a
  - docker images -a

script:
  - npm run eslint
  - npm run test
